/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_homo_superresolution_core_streamline_StreamlineNative */

#ifndef _Included_io_homo_superresolution_core_streamline_StreamlineNative
#define _Included_io_homo_superresolution_core_streamline_StreamlineNative
#ifdef __cplusplus
extern "C" {
    #endif
    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nOpen
     * Signature: (ZIJ[Ljava/lang/String;Ljava/lang/String;[IIILjava/lang/String;Ljava/lang/String;Lio/homo/superresolution/core/streamline/StreamlineLogListener;[J)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nOpen
    (JNIEnv *, jclass, jboolean, jint, jlong, jobjectArray, jstring, jintArray, jint, jint, jstring, jstring, jobject,
     jlongArray);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nClose
     * Signature: (J)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nClose
    (JNIEnv *, jclass, jlong);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nIsSessionActive
     * Signature: (J)Z
     */
    JNIEXPORT jboolean JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nIsSessionActive
    (JNIEnv *, jclass, jlong);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nInit
     * Signature: (Ljava/lang/String;Ljava/lang/String;)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nInit
    (JNIEnv *, jclass, jstring, jstring);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nShutdown
     * Signature: ()I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nShutdown
    (JNIEnv *, jclass);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nCreateVkInstance
     * Signature: (J)J
     */
    JNIEXPORT jlong JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nCreateVkInstance
    (JNIEnv *, jclass, jlong);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nCreateVkDevice
     * Signature: (JJJ)J
     */
    JNIEXPORT jlong JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nCreateVkDevice
    (JNIEnv *, jclass, jlong, jlong, jlong);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nGetLastVkResult
     * Signature: ()I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nGetLastVkResult
    (JNIEnv *, jclass);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nIsDLSSGSupported
     * Signature: ()Z
     */
    JNIEXPORT jboolean JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nIsDLSSGSupported
    (JNIEnv *, jclass);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nDLSSGSetOptions
     * Signature: (ZI)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nDLSSGSetOptions
    (JNIEnv *, jclass, jboolean, jint);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nDLSSGGetState
     * Signature: (Lio/homo/superresolution/core/streamline/StreamlineDLSSGState;)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nDLSSGGetState
    (JNIEnv *, jclass, jobject);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nSetVulkanInfo
     * Signature: (JJJJIIIIIIZIII)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nSetVulkanInfo
    (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jint, jint, jint, jint, jint, jboolean, jint, jint, jint);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nIsFeatureSupported
     * Signature: (JIJ[Z)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nIsFeatureSupported
    (JNIEnv *, jclass, jlong, jint, jlong, jbooleanArray);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nIsFeatureLoaded
     * Signature: (JI[Z)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nIsFeatureLoaded
    (JNIEnv *, jclass, jlong, jint, jbooleanArray);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nSetFeatureLoaded
     * Signature: (JIZ)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nSetFeatureLoaded
    (JNIEnv *, jclass, jlong, jint, jboolean);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nGetFeatureRequirements
     * Signature: (JILio/homo/superresolution/core/streamline/StreamlineTypes/FeatureRequirements;)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nGetFeatureRequirements
    (JNIEnv *, jclass, jlong, jint, jobject);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nGetFeatureVersion
     * Signature: (JILio/homo/superresolution/core/streamline/StreamlineTypes/FeatureVersion;)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nGetFeatureVersion
    (JNIEnv *, jclass, jlong, jint, jobject);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nGetNewFrameToken
     * Signature: (JZILio/homo/superresolution/core/streamline/StreamlineTypes/FrameToken;)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nGetNewFrameToken
    (JNIEnv *, jclass, jlong, jboolean, jint, jobject);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nSetTag
     * Signature: (JI[Lio/homo/superresolution/core/streamline/StreamlineTypes/ResourceTag;J)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nSetTag
    (JNIEnv *, jclass, jlong, jint, jobjectArray, jlong);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nSetTagForFrame
     * Signature: (JJI[Lio/homo/superresolution/core/streamline/StreamlineTypes/ResourceTag;J)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nSetTagForFrame
    (JNIEnv *, jclass, jlong, jlong, jint, jobjectArray, jlong);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nSetConstants
     * Signature: (JLio/homo/superresolution/core/streamline/StreamlineTypes/Constants;JI)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nSetConstants
    (JNIEnv *, jclass, jlong, jobject, jlong, jint);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nAllocateResources
     * Signature: (JJII)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nAllocateResources
    (JNIEnv *, jclass, jlong, jlong, jint, jint);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nFreeResources
     * Signature: (JII)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nFreeResources
    (JNIEnv *, jclass, jlong, jint, jint);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nEvaluateFeature
     * Signature: (JIJ[Lio/homo/superresolution/core/streamline/StreamlineTypes/EvaluateInput;J)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nEvaluateFeature
    (JNIEnv *, jclass, jlong, jint, jlong, jobjectArray, jlong);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nGetFeatureFunction
     * Signature: (JILjava/lang/String;[J)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nGetFeatureFunction
    (JNIEnv *, jclass, jlong, jint, jstring, jlongArray);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nDlssGetOptimalSettings
     * Signature: (JLio/homo/superresolution/core/streamline/StreamlineTypes/DlssOptions;Lio/homo/superresolution/core/streamline/StreamlineTypes/DlssOptimalSettings;)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nDlssGetOptimalSettings
    (JNIEnv *, jclass, jlong, jobject, jobject);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nDlssGetState
     * Signature: (JILio/homo/superresolution/core/streamline/StreamlineTypes/DlssState;)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nDlssGetState
    (JNIEnv *, jclass, jlong, jint, jobject);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nDlssSetOptions
     * Signature: (JILio/homo/superresolution/core/streamline/StreamlineTypes/DlssOptions;)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nDlssSetOptions
    (JNIEnv *, jclass, jlong, jint, jobject);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nDlssGGetState
     * Signature: (JILio/homo/superresolution/core/streamline/StreamlineTypes/DlssGState;Lio/homo/superresolution/core/streamline/StreamlineTypes/DlssGOptions;)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nDlssGGetState
    (JNIEnv *, jclass, jlong, jint, jobject, jobject);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nDlssGSetOptions
     * Signature: (JILio/homo/superresolution/core/streamline/StreamlineTypes/DlssGOptions;)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nDlssGSetOptions
    (JNIEnv *, jclass, jlong, jint, jobject);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nPclGetState
     * Signature: (JLio/homo/superresolution/core/streamline/StreamlineTypes/PclState;)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nPclGetState
    (JNIEnv *, jclass, jlong, jobject);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nPclSetMarker
     * Signature: (JIJ)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nPclSetMarker
    (JNIEnv *, jclass, jlong, jint, jlong);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nPclSetOptions
     * Signature: (JLio/homo/superresolution/core/streamline/StreamlineTypes/PclOptions;)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nPclSetOptions
    (JNIEnv *, jclass, jlong, jobject);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nReflexGetState
     * Signature: (JLio/homo/superresolution/core/streamline/StreamlineTypes/ReflexState;)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nReflexGetState
    (JNIEnv *, jclass, jlong, jobject);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nReflexSleep
     * Signature: (JJ)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nReflexSleep
    (JNIEnv *, jclass, jlong, jlong);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nReflexSetOptions
     * Signature: (JLio/homo/superresolution/core/streamline/StreamlineTypes/ReflexOptions;)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nReflexSetOptions
    (JNIEnv *, jclass, jlong, jobject);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nReflexSetCameraData
     * Signature: (JIJLio/homo/superresolution/core/streamline/StreamlineTypes/ReflexCameraData;)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nReflexSetCameraData
    (JNIEnv *, jclass, jlong, jint, jlong, jobject);

    /*
     * Class:     io_homo_superresolution_core_streamline_StreamlineNative
     * Method:    nReflexGetPredictedCameraData
     * Signature: (JIJLio/homo/superresolution/core/streamline/StreamlineTypes/ReflexPredictedCameraData;)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_streamline_StreamlineNative_nReflexGetPredictedCameraData
    (JNIEnv *, jclass, jlong, jint, jlong, jobject);

    #ifdef __cplusplus
}
#endif
#endif
