/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_homo_superresolution_core_ngx_NgxNative */

#ifndef _Included_io_homo_superresolution_core_ngx_NgxNative
#define _Included_io_homo_superresolution_core_ngx_NgxNative
#ifdef __cplusplus
extern "C" {
    #endif
    /*
     * Class:     io_homo_superresolution_core_ngx_NgxNative
     * Method:    nInitWithProjectId
     * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;JJJJJLio/homo/superresolution/core/ngx/NgxFeatureCommonInfo;I)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_ngx_NgxNative_nInitWithProjectId
    (JNIEnv *, jclass, jstring, jint, jstring, jstring, jlong, jlong, jlong, jlong, jlong, jobject, jint);

    /*
     * Class:     io_homo_superresolution_core_ngx_NgxNative
     * Method:    nShutdown
     * Signature: ()I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_ngx_NgxNative_nShutdown
    (JNIEnv *, jclass);

    /*
     * Class:     io_homo_superresolution_core_ngx_NgxNative
     * Method:    nGetFeatureRequirements
     * Signature: (JJLio/homo/superresolution/core/ngx/NgxFeatureDiscoveryInfo;Lio/homo/superresolution/core/ngx/NgxFeatureRequirement;)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_ngx_NgxNative_nGetFeatureRequirements
    (JNIEnv *, jclass, jlong, jlong, jobject, jobject);

    /*
     * Class:     io_homo_superresolution_core_ngx_NgxNative
     * Method:    nAllocateParameters
     * Signature: (Lio/homo/superresolution/core/ngx/NgxParameters;)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_ngx_NgxNative_nAllocateParameters
    (JNIEnv *, jclass, jobject);

    /*
     * Class:     io_homo_superresolution_core_ngx_NgxNative
     * Method:    nGetCapabilityParameters
     * Signature: (Lio/homo/superresolution/core/ngx/NgxParameters;)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_ngx_NgxNative_nGetCapabilityParameters
    (JNIEnv *, jclass, jobject);

    /*
     * Class:     io_homo_superresolution_core_ngx_NgxNative
     * Method:    nDestroyParameters
     * Signature: (J)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_ngx_NgxNative_nDestroyParameters
    (JNIEnv *, jclass, jlong);

    /*
     * Class:     io_homo_superresolution_core_ngx_NgxNative
     * Method:    nCreateFeature
     * Signature: (JIJLio/homo/superresolution/core/ngx/NgxFeature;)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_ngx_NgxNative_nCreateFeature
    (JNIEnv *, jclass, jlong, jint, jlong, jobject);

    /*
     * Class:     io_homo_superresolution_core_ngx_NgxNative
     * Method:    nReleaseFeature
     * Signature: (J)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_ngx_NgxNative_nReleaseFeature
    (JNIEnv *, jclass, jlong);

    /*
     * Class:     io_homo_superresolution_core_ngx_NgxNative
     * Method:    nEvaluateFeature
     * Signature: (JJJLio/homo/superresolution/core/ngx/NgxProgressCallback;)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_ngx_NgxNative_nEvaluateFeature
    (JNIEnv *, jclass, jlong, jlong, jlong, jobject);

    /*
     * Class:     io_homo_superresolution_core_ngx_NgxNative
     * Method:    nParametersSetUnsignedLong
     * Signature: (JLjava/lang/String;J)V
     */
    JNIEXPORT void JNICALL Java_io_homo_superresolution_core_ngx_NgxNative_nParametersSetUnsignedLong
    (JNIEnv *, jclass, jlong, jstring, jlong);

    /*
     * Class:     io_homo_superresolution_core_ngx_NgxNative
     * Method:    nParametersSetFloat
     * Signature: (JLjava/lang/String;F)V
     */
    JNIEXPORT void JNICALL Java_io_homo_superresolution_core_ngx_NgxNative_nParametersSetFloat
    (JNIEnv *, jclass, jlong, jstring, jfloat);

    /*
     * Class:     io_homo_superresolution_core_ngx_NgxNative
     * Method:    nParametersSetDouble
     * Signature: (JLjava/lang/String;D)V
     */
    JNIEXPORT void JNICALL Java_io_homo_superresolution_core_ngx_NgxNative_nParametersSetDouble
    (JNIEnv *, jclass, jlong, jstring, jdouble);

    /*
     * Class:     io_homo_superresolution_core_ngx_NgxNative
     * Method:    nParametersSetUnsignedInt
     * Signature: (JLjava/lang/String;J)V
     */
    JNIEXPORT void JNICALL Java_io_homo_superresolution_core_ngx_NgxNative_nParametersSetUnsignedInt
    (JNIEnv *, jclass, jlong, jstring, jlong);

    /*
     * Class:     io_homo_superresolution_core_ngx_NgxNative
     * Method:    nParametersSetInt
     * Signature: (JLjava/lang/String;I)V
     */
    JNIEXPORT void JNICALL Java_io_homo_superresolution_core_ngx_NgxNative_nParametersSetInt
    (JNIEnv *, jclass, jlong, jstring, jint);

    /*
     * Class:     io_homo_superresolution_core_ngx_NgxNative
     * Method:    nParametersSetPointer
     * Signature: (JLjava/lang/String;J)V
     */
    JNIEXPORT void JNICALL Java_io_homo_superresolution_core_ngx_NgxNative_nParametersSetPointer
    (JNIEnv *, jclass, jlong, jstring, jlong);

    /*
     * Class:     io_homo_superresolution_core_ngx_NgxNative
     * Method:    nParametersGetUnsignedLong
     * Signature: (JLjava/lang/String;[J)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_ngx_NgxNative_nParametersGetUnsignedLong
    (JNIEnv *, jclass, jlong, jstring, jlongArray);

    /*
     * Class:     io_homo_superresolution_core_ngx_NgxNative
     * Method:    nParametersGetFloat
     * Signature: (JLjava/lang/String;[F)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_ngx_NgxNative_nParametersGetFloat
    (JNIEnv *, jclass, jlong, jstring, jfloatArray);

    /*
     * Class:     io_homo_superresolution_core_ngx_NgxNative
     * Method:    nParametersGetDouble
     * Signature: (JLjava/lang/String;[D)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_ngx_NgxNative_nParametersGetDouble
    (JNIEnv *, jclass, jlong, jstring, jdoubleArray);

    /*
     * Class:     io_homo_superresolution_core_ngx_NgxNative
     * Method:    nParametersGetUnsignedInt
     * Signature: (JLjava/lang/String;[J)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_ngx_NgxNative_nParametersGetUnsignedInt
    (JNIEnv *, jclass, jlong, jstring, jlongArray);

    /*
     * Class:     io_homo_superresolution_core_ngx_NgxNative
     * Method:    nParametersGetInt
     * Signature: (JLjava/lang/String;[I)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_ngx_NgxNative_nParametersGetInt
    (JNIEnv *, jclass, jlong, jstring, jintArray);

    /*
     * Class:     io_homo_superresolution_core_ngx_NgxNative
     * Method:    nParametersGetPointer
     * Signature: (JLjava/lang/String;[J)I
     */
    JNIEXPORT jint JNICALL Java_io_homo_superresolution_core_ngx_NgxNative_nParametersGetPointer
    (JNIEnv *, jclass, jlong, jstring, jlongArray);

    /*
     * Class:     io_homo_superresolution_core_ngx_NgxNative
     * Method:    nParametersReset
     * Signature: (J)V
     */
    JNIEXPORT void JNICALL Java_io_homo_superresolution_core_ngx_NgxNative_nParametersReset
    (JNIEnv *, jclass, jlong);

    #ifdef __cplusplus
}
#endif
#endif
